syntax = "proto3";
package messenger;
option go_package = "./gen";

import "google/protobuf/timestamp.proto";

message Reaction {
  string user = 1;
  string emoji = 2;
}

message Message {
  string id = 1;
  string user = 2;
  string text = 3;
  google.protobuf.Timestamp created_at = 4;
  repeated Reaction reactions = 5;
}

message ReactionRequest {
  string message_id = 1;
  Reaction reaction = 2;
}

message ReactionResponse {
  bool success = 1;
}

message DeleteMessagesRequest {
  repeated Message messages = 1;
}

message DeleteMessagesResponse {
  bool success = 1;
}

message ClientListRequest {}

message ClientListResponse {
  repeated string clients = 1;
}

message GetHistoryRequest {
  int32 limit = 1;
  string room = 2;
}

message GetHistoryResponse {
  repeated Message messages = 1;
}

service ChatService {
  rpc Chat(stream Message) returns (stream Message);
  rpc GetClients(ClientListRequest) returns (ClientListResponse);
  rpc GetHistory(GetHistoryRequest) returns (GetHistoryResponse);
  rpc DeleteMessages(DeleteMessagesRequest) returns (DeleteMessagesResponse);
  rpc SetReaction(ReactionRequest) returns (ReactionResponse);
}
