package lavender.client.android.theme

object BuiltInThemes {
    private const val LAVENDER_MIST = "#967BB6"

    val baseLight: Theme = Theme(
        id = "builtin_graphite",
        name = "Графит и золото",
        primaryColor = "#85754E",
        backgroundColor = "#F5F5F5",
        surfaceColor = "#FFFFFF",
        surfaceContainer = "#E0E0E0",
        textPrimaryColor = "#212121",
        textSecondaryColor = "#666666",
        onPrimaryColor = "#FFFFFF",
        onSurfaceColor = "#424242",
        bottomPanelColor = "#FFFFFF",
        onBottomPanelColor = "#85754E",
        outgoingBubbleColor = "#85754E",
        incomingBubbleColor = "#E0E0E0",
        chatListBackgroundImageUrl = "",
        chatBackgroundImageUrl = "",
    )

    val dark: Theme = Theme(
        id = "dark",
        name = "Системная темная",
        primaryColor = LAVENDER_MIST,
        backgroundColor = "#04052E",
        surfaceColor = "#1A1B46",
        surfaceContainer = "#1A1B46",
        textPrimaryColor = "#FFFFFF",
        textSecondaryColor = "#E0E0E0",
        onPrimaryColor = "#FFFFFF",
        onSurfaceColor = "#E0E0E0",
        bottomPanelColor = "#1A1B46",
        onBottomPanelColor = LAVENDER_MIST,
        outgoingBubbleColor = "#2A2C6D",
        incomingBubbleColor = "#16173A",
        chatListBackgroundImageUrl = "",
        chatBackgroundImageUrl = "",
    )

    val all: List<Theme> = listOf(
        baseLight.copy(
            id = "builtin_green",
            name = "Зеленый лес",
            primaryColor = "#2E7D32",
            backgroundColor = "#F8FAF5",
            surfaceColor = "#EEF7E2",
            surfaceContainer = "#E1EDD1",
            textPrimaryColor = "#144218",
            onSurfaceColor = "#33691E",
            onBottomPanelColor = "#2E7D32",
            outgoingBubbleColor = "#2E7D32",
            incomingBubbleColor = "#E1EDD1",
        ),
        baseLight.copy(
            id = "builtin_blue",
            name = "Современный синий",
            primaryColor = "#007AFF",
            backgroundColor = "#E3F2FD",
            surfaceColor = "#FFFFFF",
            surfaceContainer = "#D1E9FF",
            textPrimaryColor = "#1C1C1E",
            onSurfaceColor = "#3A3A3C",
            bottomPanelColor = "#E3F2FD",
            onBottomPanelColor = "#1565C0",
            outgoingBubbleColor = "#007AFF",
            incomingBubbleColor = "#D1E9FF",
        ),
        baseLight.copy(
            id = "builtin_purple",
            name = "Королевский пурпур",
            primaryColor = "#6A1B9A",
            backgroundColor = "#FBF8FF",
            surfaceColor = "#F0E2F5",
            surfaceContainer = "#E8D0F0",
            textPrimaryColor = "#2D0C54",
            onSurfaceColor = "#4A148C",
            onBottomPanelColor = "#6A1B9A",
            outgoingBubbleColor = "#6A1B9A",
            incomingBubbleColor = "#E8D0F0",
        ),
        baseLight.copy(
            id = "builtin_sunset",
            name = "Закатный оранжевый",
            primaryColor = "#D84315",
            backgroundColor = "#FFF3E0",
            surfaceColor = "#FFE0B2",
            surfaceContainer = "#FFD180",
            textPrimaryColor = "#BF360C",
            onSurfaceColor = "#E65100",
            bottomPanelColor = "#FFF3E0",
            onBottomPanelColor = "#D84315",
            outgoingBubbleColor = "#D84315",
            incomingBubbleColor = "#FFD180",
        ),
        baseLight.copy(
            id = "builtin_graphite",
            name = "Графит и золото",
            outgoingBubbleColor = "#85754E",
            incomingBubbleColor = "#E0E0E0",
        ),
        baseLight.copy(
            id = "builtin_rose",
            name = "Северная роза",
            primaryColor = "#B08990",
            backgroundColor = "#EAECEF",
            surfaceColor = "#F9F6F7",
            surfaceContainer = "#D8DCE3",
            textPrimaryColor = "#443C3D",
            onSurfaceColor = "#5E5455",
            bottomPanelColor = "#EAECEF",
            onBottomPanelColor = "#B08990",
            outgoingBubbleColor = "#B08990",
            incomingBubbleColor = "#D8DCE3",
        ),
        baseLight.copy(
            id = "builtin_mint",
            name = "Кибер Мята",
            primaryColor = "#00BFA5",
            backgroundColor = "#F1FBF9",
            surfaceColor = "#FFFFFF",
            surfaceContainer = "#D7F2ED",
            textPrimaryColor = "#002B26",
            onSurfaceColor = "#004D40",
            onBottomPanelColor = "#00BFA5",
            outgoingBubbleColor = "#00BFA5",
            incomingBubbleColor = "#D7F2ED",
        ),
    )

    fun findById(id: String): Theme? = all.find { it.id == id }
}

